blank_issues_enabled: false
issue_templates:
  - name: Epic
    description: Whole detailled feature which contain subdivision of features. Should not be referenced in commits as we should work on childs.
    body: epic.yml
  - name: Issue
    description: Task, Bug, Feature...
    body: issue.yml