name: EPIC
description: Whole detailed feature which contains subdivisions of features. Should not be referenced in commits as we should work on child issues.
title: ""
labels: ["Epic"]
#issue_type: "Epic"
body:
  - type: markdown
    attributes:
      value: |
        _____
        > THE EPIC IS THE SOURCE OF TRUTH

        > GIVE DETAILS ABOUT THE UNDERLYING FEATURE AS MUCH AS POSSIBLE
        ___
