name: EPIC
description: Whole detailed feature which contains subdivisions of features. Should not be referenced in commits as we should work on child issues.
labels: ["Epic"]
#issue_type: "Epic"
body:
  - type: markdown
    attributes:
      value: |
        _____
        The epic is the **source of truth** !

        Please give details about the underlying feature AS MUCH AS POSSIBLE and sub-divide into small issues linked to this one.
        ___

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What's the context? What's the motivations? What's the current bahavior? What has to be changed?
      placeholder: |
        ### Context

        ### Why?

        ### Current behavior

        ### Todo

  - type: textarea
    id: mockups
    attributes:
      label: Mockups
      description: Please do your best to find mock-ups...
      placeholder: |
        Copy/past images or add files here

  - type: textarea
    id: successconditions
    attributes:
      label: Success conditions
      description: Generic success conditions (could be moved to sub-issues later)
      placeholder: |
          - [ ] As a user...
          - [ ] As an admintrator...

  - type: textarea
    id: tech
    attributes:
      label: Technical constraints
      description: Technical constraints that should be respected
      placeholder: |
          - [ ] ...
          - [ ] ...
        
  - type: markdown
    attributes:
      value: |
        > ⚠️ **Please don't forget to choose Epic as issue type** 
