name: EPIC
description: Whole detailed feature which contains subdivisions of features. Should not be referenced in commits as we should work on child issues.
title: "[EPIC] Titre de l'EPIC"
labels: ["epic"]
body:
  - type: markdown
    attributes:
      value: |
        ## Description
        Décrivez l'objectif de cette EPIC.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Décrivez l'objectif de cette EPIC.
      placeholder: Décrivez l'objectif de cette EPIC.
      value: |
        ## Description
        Décrivez l'objectif de cette EPIC.

  - type: checkboxes
    id: tasks
    attributes:
      label: Tâches
      description: Liste des tâches à accomplir.
      options:
        - label: Tâche 1
        - label: Tâche 2
        - label: Tâche 3
