name: Patch
description: Something to fast patch in production
labels: ["Patch"]
body:
  - type: textarea
    id: description
    description:  ⚠️ Please, brief explain of what has to be test once the patch deployed
    validations:
      required: true
    attributes:
      label: Description

  - type: markdown
    attributes:
      value: |
        ______
        > ⚠️ ⚠️ **Please don't forget to choose "Bug" as issue type** ⚠️ ⚠️
        ______
