name: Trigger Auto-Fill PR

on:
  workflow_dispatch:

jobs:
  trigger-devops-workflow:
    uses: regmind-eu/devops/.github/workflows/pr-autofill.yml@main
    with:
      repo_name: ${{ github.repository }}
      pr_number: ${{ github.event.pull_request.number }}